---
version: '3.8'
services:
  nginx-waf-alpine:
    image: aoukltddocker/nginx-proxy:v0.1
    build:
      context: .
      dockerfile: v3-nginx/Dockerfile-alpine
      cache_from:
        - aoukltddocker/nginx-proxy:v0.1
    environment:
      SERVER_NAME: _
      PORT: "80"
      SSL_PORT: "443"
      # DNS_SERVER: "1.1.1.1"
      METRICS_ALLOW_FROM: all
      NGINX_ALWAYS_TLS_REDIRECT: "on"
      MODSEC_RULE_ENGINE: "On"
    ports:
      - "8080:80"
      - "8443:443"
    # user: "10001"
    depends_on:
      - backend
    volumes:
      - ./conf.d/default.conf.template:/etc/nginx/templates/conf.d/default.conf.template
  backend:
    image: docker.io/kennethreitz/httpbin
